name: app
description: "Predict your friends and foes alike."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.0
  google_fonts: ^8.0.0
  go_router: ^17.0.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  flutter_secure_storage: ^10.0.0
  dio: ^5.9.1
  flutter_regex: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-removebg-preview.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
